# 01-Cars

![](https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)
Picture by [Alex Suprun](https://unsplash.com/photos/A53o1drQS2k)

Now let's practice with a cars dataset what we learnt in the lecture.

Begin by importing pandas and numpy using the standard convention:

In [1]:
# TODO: Import numpy and pandas with the right convention
### STRIP_START ###

### STRIP_END ###
import numpy as np
import pandas as pd

Now load the file *Automobile_data.csv* into the variable *cars* and display the first lines:

In [18]:
# TODO: load the dataset contained in the file Automobile_data.csv
# and then display the first 10 lines
### STRIP_START ###
cars = pd.read_csv('Automobile_data.csv')
cars[:1]
### STRIP_END ###

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495

Is there missing data? Replace it with NaN and display again the first lines to check it worked well:

In [23]:
#Â TODO: identify how the missing data is filled and replace it with NaN
# and then display again the first ten lines to check it has worked
### STRIP_START ###
cars = pd.read_csv('Automobile_data.csv', na_values=['?'])
cars['normalized-losses'] = cars['normalized-losses'].fillna(cars['normalized-losses'].dropna())

### STRIP_END ###

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
197,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,24,28,16515.0
198,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100.0,17,22,18420.0
199,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100.0,17,22,18950.0
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

Display the last 8 rows:

In [24]:
# TODO: display the last 8 rows of cars
### STRIP_START ###
cars[-8:]
### STRIP_END ###

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
197,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,24,28,16515.0
198,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100.0,17,22,18420.0
199,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100.0,17,22,18950.0
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

Print the information of the dataframe using *info*

In [27]:
# TODO: Print out the information of the dataframe
### STRIP_START ###
cars.info()
### STRIP_END ###

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized-losses    164 non-null float64
make                 205 non-null object
fuel-type            205 non-null object
aspiration           205 non-null object
num-of-doors         203 non-null object
body-style           205 non-null object
drive-wheels         205 non-null object
engine-location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb-weight          205 non-null int64
engine-type          205 non-null object
num-of-cylinders     205 non-null object
engine-size          205 non-null int64
fuel-system          205 non-null object
bore                 201 non-null float64
stroke               201 non-null float64
compression-ratio    205 non-null float64
horsepower           203 non-null float64
peak-rpm             203 non-null float64
city-mpg             205 non-null int64
highway-mpg          205 non-null int64
price                201 non-null float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.7+ KB

Now select only the cars with a value in 'price' and put it in a new dataframe called *cars_with_price*. Then print the shape of this *cars_with_price* dataframe.

In [35]:
# TODO: select the cars with a price in the variable cars_with_price
### STRIP_START ###
cars_with_price = cars['price']
cars_with_price
### STRIP_END ###

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
5      15250.0
6      17710.0
7      18920.0
8      23875.0
9          NaN
10     16430.0
11     16925.0
12     20970.0
13     21105.0
14     24565.0
15     30760.0
16     41315.0
17     36880.0
18      5151.0
19      6295.0
20      6575.0
21      5572.0
22      6377.0
23      7957.0
24      6229.0
25      6692.0
26      7609.0
27      8558.0
28      8921.0
29     12964.0
        ...
175     9988.0
176    10898.0
177    11248.0
178    16558.0
179    15998.0
180    15690.0
181    15750.0
182     7775.0
183     7975.0
184     7995.0
185     8195.0
186     8495.0
187     9495.0
188     9995.0
189    11595.0
190     9980.0
191    13295.0
192    13845.0
193    12290.0
194    12940.0
195    13415.0
196    15985.0
197    16515.0
198    18420.0
199    18950.0
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

You should get a shape of (201, 26).

Can you tell how many cars don't have a price?

In [38]:
# TODO: how many cars do not have a price
### STRIP_START ###
cars_with_price.isna().sum() 
### STRIP_END ###

4

How many constructors ('make' column) are in the dataset?

In [42]:
# TODO: print how many mobile constructors ('make') are present in the dataset
### STRIP_START ###
make = cars['make'].value_counts()
make
### STRIP_END ###

toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
volvo            11
peugot           11
dodge             9
bmw               8
mercedes-benz     8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: make, dtype: int64

Print the constructors that have more than 10 models:

In [48]:
# TODO: what are the makers who have more than 10 models?
### STRIP_START ###
cars_make= make > 10
cars_make
### STRIP_END ###

toyota            True
nissan            True
mazda             True
mitsubishi        True
honda             True
volkswagen        True
subaru            True
volvo             True
peugot            True
dodge            False
bmw              False
mercedes-benz    False
audi             False
plymouth         False
saab             False
porsche          False
isuzu            False
jaguar           False
chevrolet        False
alfa-romero      False
renault          False
mercury          False
Name: make, dtype: bool

Print the following statistics:

In [56]:
# TODO: print the maximum horsepower
### STRIP_START ###

print('max values:', cars['horsepower'].max())

### STRIP_END ###

# TODO: print the minimum length
### STRIP_START ###
print('min values:', cars['length'].min())
### STRIP_END ###

# TODO: print the mean width
### STRIP_START ###
print('min values:', cars['width'].mean())
### STRIP_END ###

# TODO: print the standard deviation of height
### STRIP_START ###
print('standard deviation values:', cars['height'].std())
### STRIP_END ###

max values: 288.0
min values: 141.1
min values: 65.90780487804875
standard deviation values: 2.4435219699049044